name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libtool automake autoconf pkg-config gettext build-essential openjdk-17-jdk
        pip install "pip<24.0" "setuptools<69" "cython<3.0.0" buildozer

    - name: Build with Buildozer
      run: |
        buildozer init
        sed -i 's/android.archs = arm64-v8a, armeabi-v7a/android.archs = arm64-v8a/' buildozer.spec
        yes | buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: mi-app-apk
        path: bin/*.apk
